package fotballinfo;

import javax.swing.*;
import fotballinfo.data.*;
import javax.swing.table.*;

/**
 *
 * @author Marius Geitle <geimas5@gmail.com>
 */
public class YearView extends JPanel implements IDataView {
    
    private IDataProvider dataProvider;
    private FotballInfoFrame frame;

    /**
     * Creates new form YearView
     */
    public YearView(IDataProvider provider, FotballInfoFrame frame) {
        dataProvider = provider;
        this.frame = frame;
        
        initComponents();
    }
    
    @Override
    public void LoadData() {
       LoadSeasonsTask retriever = new LoadSeasonsTask(this, dataProvider);
       retriever.execute();
    }
    
    public void SetSeasons(SeasonInfo[] data) {
        DefaultTableModel model = (DefaultTableModel)this.seasonsTable.getModel();
        model.setRowCount(0);
        
        for(SeasonInfo season : data) {
            model.addRow(new Object[] { season.getYear(), season.getMatches() });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        seasonsTable = new javax.swing.JTable();

        seasonsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Year", "Matches"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        seasonsTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        seasonsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seasonsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(seasonsTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void seasonsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seasonsTableMouseClicked
        if(this.seasonsTable.getSelectionModel().isSelectionEmpty())
            return;
        
        int year = (int)this.seasonsTable.getModel().getValueAt(this.seasonsTable.getSelectedRow(), 0);
        frame.showSeason(year);
    }//GEN-LAST:event_seasonsTableMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable seasonsTable;
    // End of variables declaration//GEN-END:variables
}
