/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package geoquiz;

import java.util.*;
import javax.swing.*;

/**
 *
 * @author mariusg
 */
public class QuizView extends javax.swing.JPanel implements IView {

    private final int numberOfQuestions = 10;
    
    private MainFrame mainFrame;
    
    private List<MultipleChoiceQuestion> questions = new ArrayList<>();
    
    private int activeQuestion = -1;
    
    /**
     * Creates new form QuizView
     */
    public QuizView(MainFrame main) {
        initComponents();
        
        this.mainFrame = main;
        
        generateQuiz();
        initialize();
    }
    
    private void initialize(){
        quizProgressBar.setMaximum(numberOfQuestions);
        quizProgressBar.setValue(0);
        generateQuiz();
        showQuestion(0);
    }
    
    private void showQuestion(int i) {
        if(activeQuestion != -1)
            questionPanel.remove(questions.get(activeQuestion));
        
        activeQuestion = i;
        
        QuestionBase question = questions.get(activeQuestion);
        questionPanel.add(question);
        question.setSize(question.getMaximumSize());
        questionPanel.revalidate();
        this.quizProgressBar.setValue(i);
    }
    
    private void generateQuiz(){
        QuestionFactory factory = QuestionFactory.GetInstance();
        
        for(int i = 0; i < numberOfQuestions; i++){
            try {
                questions.add(factory.generateQuestion());
            }
            catch(DataException ex){
               System.out.println(ex.toString());
           }
        }
    }
    
    private boolean isLastQuestion(){
        return (activeQuestion == numberOfQuestions);
    }
    
    private void nextQuestion() {
        if(questions.get(activeQuestion).isAnswered()){
            showQuestion(activeQuestion + 1);
        }
        else{
            JOptionPane.showMessageDialog(this, "You must select an answer: ");    
        }
    }
    
    private void finishQuiz(){
        int score = calculateScore(); 
        
        JOptionPane.showMessageDialog(this, "Your final score: " + score);
        this.mainFrame.showMenu();
    }
    
    private int calculateScore(){
        int correctQuestions = 0;
        for(int i = 0; i < this.questions.size(); i++){
            if(this.questions.get(i).isAnsweredCorrectly()) {
                correctQuestions++;
            }
        }
        
        return correctQuestions;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        quizProgressBar = new javax.swing.JProgressBar();
        questionPanel = new javax.swing.JPanel();
        nextButton = new javax.swing.JButton();

        javax.swing.GroupLayout questionPanelLayout = new javax.swing.GroupLayout(questionPanel);
        questionPanel.setLayout(questionPanelLayout);
        questionPanelLayout.setHorizontalGroup(
            questionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );
        questionPanelLayout.setVerticalGroup(
            questionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 369, Short.MAX_VALUE)
        );

        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(questionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(quizProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(questionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quizProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nextButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        if(!isLastQuestion()) {
            nextQuestion();
        }
        else {
            finishQuiz();
        }
    }//GEN-LAST:event_nextButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton nextButton;
    private javax.swing.JPanel questionPanel;
    private javax.swing.JProgressBar quizProgressBar;
    // End of variables declaration//GEN-END:variables
}
